### ISSUE TITLE
Add Launching Icon

### ISSUE THREAD

**Issue by forfireonly** [forfireonly/PartyParrot#3]
Missing Launching icon

**Comment by Jay206-Programmer** [comment]
Hi, Can you link the Image you want as the **Launching Icon**?

**Comment by forfireonly** [comment]
Hi, thank you for your interest, 

https://github.com/forfireonly/PartyParrot/blob/master/Parrot.png

**Comment by peculiaruc** [comment]
I am interested in this has it been assigned, if no, I want to take it up

**Comment by shash137** [comment]
> Hi, thank you for your interest,
> 
> https://github.com/forfireonly/PartyParrot/blob/master/Parrot.png

Heyy @forfireonly you want this image as app icon, may I take the issue and work on this?

**Comment by peculiaruc** [comment]
Thanks

**Comment by peculiaruc** [comment]
yes  i am adding the image as app icon

**Comment by shash137** [comment]
Hey @forfireonly app icon is already present, may replace it with the image given in the link?
Please tell

**Comment by peculiaruc** [comment]
Is already assigned to me. Please

**Comment by forfireonly** [comment]
Yes, please

**Comment by peculiaruc** [comment]
Done and sent PR
